name: ridewave
description: "A new Flutter project."

publish_to: 'none'

# App version
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # --- Core Packages ---
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  http: ^1.5.0
  intl: ^0.20.2
  logger: ^1.1.0

  # --- UI & Animation ---
  lottie: ^3.3.2
  smooth_page_indicator: ^1.2.1

  # --- Device & System ---
  url_launcher: ^6.3.2
  shared_preferences: ^2.3.2
  flutter_native_splash: ^2.4.7

  # --- Firebase (Optional Auth) ---
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  firebase_analytics: ^12.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code quality and linting
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/profile_img/
    - assets/images/icons/
    - assets/images/onboarding/
    - assets/images/images/
